### PR TITLE
Single Launch file for Thorvald & Robotnik

### PR DESCRIPTION
**Pull request by pulver22**

### CODE REVIEW

**Comment by pulver22** [comment]
Right now, the costmap is not generated when using multiple hokuyo, making the navigation impossible. I am going to include the laser merger, adjust the topics and fix this in a new commit.

**Review by marc-hanheide — APPROVED** [review]
I haven't really tested anything, but I don't see major issues with this.

**Comment by marc-hanheide** [comment]
> I haven't really tested anything, but I don't see major issues with this.

well, other than the failed CI build ;-)

**Comment by pulver22** [comment]
Yes I know that ;) I'm on it!

**Comment by pulver22** [comment]
> > I haven't really tested anything, but I don't see major issues with this.
> 
> well, other than the failed CI build ;-)
> 
> https://lcas.lincoln.ac.uk/buildfarm/job/Mpr__bacchus_lcas__ubuntu_bionic_amd64/16/testReport/

This build fails because the test file assumes there is only one hokuyo generating the `/thorvald_001/scan` topic. This condition is not met when using the laser merger which, yes, generates this topic but should be launch in a second terminal window at a later stage in order to correctly subscribe to the two laser topics and generate the merged one (see [HERE](https://github.com/iralabdisco/ira_laser_tools/issues/5)).

If we want to keep the unit test as they are, I will modify the launch file to load different sensor configuration based on a parameter and by default use the one with only one hokuyo (so to pass the test).

**Pull request merged**
