### PR TITLE
supporting GPU in docker

### PR DESCRIPTION
**Pull request by marc-hanheide**
initial work to make CUDA available

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I have made this version which contains CUDA-11-4 in the image and is confirmed to work on an NVIDIDA host (tested on coltrane). This will allow people to use GPU processing in their containers. Of course it means that the host must support the NVIDIA runtime, which should be installed on our lab machines.

**Comment by marc-hanheide** [comment]
I'm contemplating to keep this as a separate branch and push as a separate (unavoidably bigger) image to the registry with its own docker-compose file. Then people that have a GPU can use it but won't be the default.

**Comment by gcielniak** [comment]
yeap that is much better solution (and probably keeps the standard one more portable)

**Comment by nikostsagk** [comment]
Is cuda installed natively in the labs as well? When it's ready I can test it in the labs

**Comment by marc-hanheide** [comment]
unfortunately not yet, but I requested it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
